### ISSUE TITLE
Having both GL and GL32 extension results in duplicated Vulkan nvidia_icd.json files

### ISSUE THREAD

**Issue by jp7677** [flathub/org.freedesktop.Platform.GL.nvidia#112]
Hi there,

I have a standard Fedora 36 installation with NVIDIA drivers installed (x64 and i686 libraries installed) and both the `GL` and `GL32` flatpak application installed. Running `vulkaninfo` on the host shows a single GPU which matches reality. When running a Vulkan application inside flatpak however, the application sees the same device twice. 

I'm not familiar how the driver setup in flatpak works, but this looks very similar to https://github.com/negativo17/nvidia-driver/issues/95 where both the x64 and i686 nvidia driver put an Vulkan icd file with the same content into `/usr/share/vulkan/icd.d/` which made Vulkan to load the same device twice. So my completely uneducated guess would be that this lines https://github.com/flathub/org.freedesktop.Platform.GL.nvidia/blob/master/nvidia-apply-extra.c#L112 and  https://github.com/flathub/org.freedesktop.Platform.GL.nvidia/blob/master/nvidia-apply-extra.c#L463 (probably also https://github.com/flathub/org.freedesktop.Platform.GL.nvidia/blob/master/nvidia-apply-extra.c#L117) should only apply to the GL/x64 driver package. I could be wrong though.

Kind regards and thanks a lot for all your hard work!

**Comment by jp7677** [comment]
The bottles flatpak application (https://flathub.org/apps/details/com.usebottles.bottles) has a built-in health check window which show a.o. the following:
```
Graphics:
    vendors:
        nvidia:
            vendor: nvidia
            envs:
                __NV_PRIME_RENDER_OFFLOAD: '1'
                __GLX_VENDOR_LIBRARY_NAME: nvidia
                __VK_LAYER_NV_optimus: NVIDIA_only
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json
    prime:
        integrated: null
        discrete: null
```
It shows indeed two NVIDIA related Vulkan icd files.
